### ISSUE TITLE
HTTPS enforcement on Chrome 47

### ISSUE THREAD

**Issue by tyt2y3** [peers/peerjs-server#90]
https://developers.google.com/web/updates/2015/10/chrome-47-webrtc?hl=en

> Public Service Announcements
> - Starting with Chrome 47, getUserMedia() requests are only allowed from secure origins: HTTPS or localhost.
> - RTP data channel support has been removed. Any remaining applications still using RTP data channels should use the standard data channels instead.

In case anyone is wondering why now their apps do not work on Chrome.
This link is useful too:
http://www.tokbox.com/blog/the-impact-of-googles-new-chrome-security-policy-on-webrtc/

**Comment by rikkertkoppes** [comment]
This basically makes it impossible to use the peerjs cloud service for camera applications. For my project, having the cloud service available over https, would be enormously beneficial, since we can then offer a simple, cheap service without the need for people to set up their own peer servers: https://github.com/firstlegoleague/director

What is needed to have the cloud service available over https? Development time? Donations? Hosts?

**Comment by Dreadchild** [comment]
hello how can i have https?

**Comment by Diez37** [comment]
var https = require('https'),
    express = require('express'),
    ExpressPeerServer = require('peer').ExpressPeerServer;
...
var optionsHttps = {
    key: fs.readFileSync(__dirname+'/path/to/file.key'),
    cert: fs.readFileSync(__dirname+/path/to/file.crt')
};
...
var app = express();
var httpsServer = https.createServer(optionsHttps, app);
var peerServer = ExpressPeerServer(httpsServer, {});

If I understood you correctly
